### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bgainor** [bgainor/alpb-ruby#1]
- [x] Highlight queried team in results
- [ ] For games in progress, make status be inning half
- [ ] Get line and box scores
- [ ] Improve performance
- [ ] Allow more fine-tuned date queries

**Comment by bgainor** [comment]
I decided that it actually works better to highlight the winner in each game. This change works whether an individual team is queried or not.
